spring:
  application:
    name: Order Management

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?schema=public
    username: postgres
    password: docker

springdoc:
  api-docs:
    version: openapi_3_0
    path: /api-docs